SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CROSSTOOL_PREFIX arm-linux-gnueabihf)

SET(CMAKE_C_COMPILER   ${CROSSTOOL_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${CROSSTOOL_PREFIX}-g++)

# SET(VCPKG_TARGET_ARCHITECTURE arm)
# SET(VCPKG_CMAKE_SYSTEM_NAME linux)
SET(VCPKG_TARGET_TRIPLET arm-linux)
