[build]
# https://github.com/rust-lang/rust/issues/79206
# rustflags = ["-C", "target-feature=+crt-static"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-self-contained=no"]
# linker = "x86_64-alpine-linux-musl-c++"