// This file is generated by rust-protobuf 2.18.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `forum.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_1;

#[derive(PartialEq,Clone,Default)]
pub struct CreatePostRequest {
    // message fields
    pub subject: ::std::string::String,
    pub content_type: ::std::string::String,
    pub body: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CreatePostRequest {
    fn default() -> &'a CreatePostRequest {
        <CreatePostRequest as ::protobuf::Message>::default_instance()
    }
}

impl CreatePostRequest {
    pub fn new() -> CreatePostRequest {
        ::std::default::Default::default()
    }

    // string subject = 1;


    pub fn get_subject(&self) -> &str {
        &self.subject
    }
    pub fn clear_subject(&mut self) {
        self.subject.clear();
    }

    // Param is passed by value, moved
    pub fn set_subject(&mut self, v: ::std::string::String) {
        self.subject = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_subject(&mut self) -> &mut ::std::string::String {
        &mut self.subject
    }

    // Take field
    pub fn take_subject(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.subject, ::std::string::String::new())
    }

    // string content_type = 2;


    pub fn get_content_type(&self) -> &str {
        &self.content_type
    }
    pub fn clear_content_type(&mut self) {
        self.content_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_content_type(&mut self, v: ::std::string::String) {
        self.content_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_content_type(&mut self) -> &mut ::std::string::String {
        &mut self.content_type
    }

    // Take field
    pub fn take_content_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.content_type, ::std::string::String::new())
    }

    // string body = 3;


    pub fn get_body(&self) -> &str {
        &self.body
    }
    pub fn clear_body(&mut self) {
        self.body.clear();
    }

    // Param is passed by value, moved
    pub fn set_body(&mut self, v: ::std::string::String) {
        self.body = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_body(&mut self) -> &mut ::std::string::String {
        &mut self.body
    }

    // Take field
    pub fn take_body(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.body, ::std::string::String::new())
    }
}

impl ::protobuf::Message for CreatePostRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.subject)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.content_type)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.body)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.subject.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.subject);
        }
        if !self.content_type.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.content_type);
        }
        if !self.body.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.body);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.subject.is_empty() {
            os.write_string(1, &self.subject)?;
        }
        if !self.content_type.is_empty() {
            os.write_string(2, &self.content_type)?;
        }
        if !self.body.is_empty() {
            os.write_string(3, &self.body)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CreatePostRequest {
        CreatePostRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "subject",
                |m: &CreatePostRequest| { &m.subject },
                |m: &mut CreatePostRequest| { &mut m.subject },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "content_type",
                |m: &CreatePostRequest| { &m.content_type },
                |m: &mut CreatePostRequest| { &mut m.content_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "body",
                |m: &CreatePostRequest| { &m.body },
                |m: &mut CreatePostRequest| { &mut m.body },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CreatePostRequest>(
                "CreatePostRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CreatePostRequest {
        static instance: ::protobuf::rt::LazyV2<CreatePostRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CreatePostRequest::new)
    }
}

impl ::protobuf::Clear for CreatePostRequest {
    fn clear(&mut self) {
        self.subject.clear();
        self.content_type.clear();
        self.body.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CreatePostRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CreatePostRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bforum.proto\x1a\tnut.proto\"d\n\x11CreatePostRequest\x12\x18\n\x07\
    subject\x18\x01\x20\x01(\tR\x07subject\x12!\n\x0ccontent_type\x18\x02\
    \x20\x01(\tR\x0bcontentType\x12\x12\n\x04body\x18\x03\x20\x01(\tR\x04bod\
    y27\n\x0cForumService\x12'\n\nCreatePost\x12\x12.CreatePostRequest\x1a\
    \x03.Ok\"\0J\xa8\x03\n\x06\x12\x04\0\0\x0f\x01\n\x08\n\x01\x0c\x12\x03\0\
    \0\x12\n\x87\x01\n\x02\x03\0\x12\x03\x02\0\x13\"|\x20import\x20\"google/\
    protobuf/empty.proto\";\n\x20import\x20\"google/protobuf/timestamp.proto\
    \";\n\x20import\x20\"google/protobuf/duration.proto\";\n\n\n\n\x02\x06\0\
    \x12\x04\x07\0\t\x01\n\n\n\x03\x06\0\x01\x12\x03\x07\x08\x14\n\x0b\n\x04\
    \x06\0\x02\0\x12\x03\x08\x022\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x08\
    \x06\x10\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\x08\x11\"\n\x0c\n\x05\x06\0\
    \x02\0\x03\x12\x03\x08,.\n\n\n\x02\x04\0\x12\x04\x0b\0\x0f\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x0b\x08\x19\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0c\x02\
    \x15\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0c\x02\x08\n\x0c\n\x05\x04\0\
    \x02\0\x01\x12\x03\x0c\t\x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0c\x13\
    \x14\n\x0b\n\x04\x04\0\x02\x01\x12\x03\r\x02\x1a\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\r\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\r\t\x15\
    \n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\r\x18\x19\n\x0b\n\x04\x04\0\x02\
    \x02\x12\x03\x0e\x02\x12\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0e\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x0e\t\r\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x0e\x10\x11b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
