SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CROSSTOOL_PREFIX /opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf)

SET(CMAKE_C_COMPILER   ${CROSSTOOL_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${CROSSTOOL_PREFIX}-g++)

SET(PKG_CONFIG_ALLOW_CROSS 1)
SET(PKG_CONFIG_DIR "")
SET(PKG_CONFIG_LIBDIR /usr/lib/arm-linux-gnueabihf/pkgconfig)