// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: forum.proto

#include "forum.pb.h"
#include "forum.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ForumService_method_names[] = {
  "/ForumService/CreatePost",
};

std::unique_ptr< ForumService::Stub> ForumService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ForumService::Stub> stub(new ForumService::Stub(channel));
  return stub;
}

ForumService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreatePost_(ForumService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ForumService::Stub::CreatePost(::grpc::ClientContext* context, const ::CreatePostRequest& request, ::Ok* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CreatePostRequest, ::Ok, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreatePost_, context, request, response);
}

void ForumService::Stub::experimental_async::CreatePost(::grpc::ClientContext* context, const ::CreatePostRequest* request, ::Ok* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CreatePostRequest, ::Ok, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePost_, context, request, response, std::move(f));
}

void ForumService::Stub::experimental_async::CreatePost(::grpc::ClientContext* context, const ::CreatePostRequest* request, ::Ok* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Ok>* ForumService::Stub::PrepareAsyncCreatePostRaw(::grpc::ClientContext* context, const ::CreatePostRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Ok, ::CreatePostRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreatePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Ok>* ForumService::Stub::AsyncCreatePostRaw(::grpc::ClientContext* context, const ::CreatePostRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreatePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

ForumService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ForumService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ForumService::Service, ::CreatePostRequest, ::Ok, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ForumService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CreatePostRequest* req,
             ::Ok* resp) {
               return service->CreatePost(ctx, req, resp);
             }, this)));
}

ForumService::Service::~Service() {
}

::grpc::Status ForumService::Service::CreatePost(::grpc::ServerContext* context, const ::CreatePostRequest* request, ::Ok* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


